version: "3.8"

services:
  nginx:
    image: nginx:1.21.1-alpine
    hostname: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
        - app
    networks:
      main:
        aliases:
          - nginx

  app:
    #TODO CREATE ENV
#    extends:
#      file: ./env.yml
#      service: base
    build:
      context: .
    container_name: tellme_local
    image: tellme:local
    restart: unless-stopped
    volumes:
      - ./src:/app:rw
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    expose:
      - "8000"
    networks:
      main:
        aliases:
            - web

networks:
  main: