# Generated by Django 4.0.5 on 2022-06-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellme', '0002_remove_category_items_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
