# Generated by Django 4.0.5 on 2022-06-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellme', '0003_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='player',
        ),
        migrations.AddField(
            model_name='score',
            name='name',
            field=models.CharField(default=1, help_text='Player/Team Name', max_length=50),
            preserve_default=False,
        ),
    ]
