# Generated by Django 4.0.5 on 2022-06-29 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tellme', '0004_remove_score_player_score_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category Selected', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tellme.category'),
        ),
    ]
