# Generated by Django 4.0.5 on 2022-06-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellme', '0005_alter_score_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='answer',
        ),
        migrations.AddField(
            model_name='score',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
