# Generated by Django 4.0.5 on 2022-06-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellme', '0006_remove_score_answer_score_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_link',
            field=models.TextField(blank=True, default='https://images.unsplash.com/photo-1618022325802-7e5e732d97a1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=748&q=80'),
        ),
    ]
